// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]); 
		int greaterCount = 0;
		int lessCount = 0;
		for (int i = 0; i < n; i++) {
			double check = Math.random();
			if (check > 0.5) {
				greaterCount ++; 
			} else {
				lessCount ++; 
			}
		}
		double ratio = 0; 
		if (greaterCount < lessCount) {
			ratio = (double) greaterCount / (double) lessCount; 
		} else {
			ratio = (double) lessCount / (double) greaterCount; 
		}
		System.out.println("> 0.5: " + greaterCount + " times");
		System.out.println("<= 0.5: " + lessCount + " times");
		if (ratio != 0) {
			System.out.println("Ratio: " + ratio);
		}
		
	}
}